### ISSUE TITLE
Identify Areas of Focus for Remainder of Phase 3

### ISSUE THREAD

**Issue by mheadd** [18F/data-federation-project#127]
## User story
As a team member, I want to know what we want to deliver at the end of Phase 3 so that I can create a plan to get there. 
  
## Acceptance criteria
- [x] Clarify amount of time remaining based on current burn rate _(Mark)_
- [x] Scope work based on hours left in current phase _(Julia)_
- [x] Brainstorm possible _specific_ Phase 3 deliverables _(Julia & Ethan)_
- [x] Discuss as a team
- [x] Agree on focus area

**Comment by juliaklindpaintner** [comment]
This issue is about narrowing our focus for the remainder of Phase 3 and set an ambitious but realistic goal. While the U.S. Data Federation has the potential to offer a broad range of tools, services, and resources, I think it's hard to try to evaluate in the abstract which potential tools or services will have the most impact. Instead, I think we should work on whatever is most concrete and worry about how it fits in to the broader U.S. Data Federation project later. 

For example, since we have really spent the most time working with the data ingest tool, perhaps we should confine our focus to that and spend the rest of the time developing the "generic" version of the tool, so that at the end of Phase 3 we would have a clear picture about how an agency partner would approach using the tool in the future. 

@ethanheppner and I are going to do some brainstorming both around concrete deliverables as well as concrete ways to engage another use case.

**Comment by juliaklindpaintner** [comment]
After a co-working session with @ethanheppner and a conversation with @mheadd I'm inclined to say we should focus on the "generic" version of the data ingest tool. We have already invested a lot of time in that tool, but we haven't validated that it is reusable, or developed a good sense of how another use case would go about using it. This would require us focusing on finding a use case that is doing something very similar to what FNS is doing now.

In order to do this, we might take the following steps:
- [ ] Talk to FNS to see if they have/know of another use case for this tool at USDA
- [ ] Come up with a more accessible name for the django data ingest tool
- [ ] Developing materials that talk more specifically about the tool and solicit other use cases doing the same thing.
- [ ] Get Amy's input around what would need to happen to make this tool implementable on another use case (document the customization work she has done, think about ways to make it more user-friendly, etc)
- [ ] Make contact with additional use cases and find out what their scenario is and what their data looks like — this would allow us to extrapolate about certain features and document concrete other use cases for the tool
- [ ] Come up with possible business models for the tool as a service / product
- [ ] Possibly get another use case to try to implement it.

**Comment by juliaklindpaintner** [comment]
@mheadd provided an update on the burn: We currently have nearly 1700 hours remaining, which would translate into 13 weeks for 4 people full time, give or take. However, since Mark and Ethan won't be full time, we probably have closer to 15 weeks left. That's approximately through the end of May/first week of June.

**Comment by juliaklindpaintner** [comment]
I'm calling this complete having discussed and agreed on the [4 workstreams](https://docs.google.com/document/d/1dYwGniGYRSqtxQPLU1TXGpzplgSXU54aRU5n5w9RZ-U/edit#) we're going to focus on for the remainder of Phase 3.
