### ISSUE TITLE
Create outline for FNS Data Validation Service Developers' Guide

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/data-federation-project#179]
## Overview

As a developer supporting the FNS Data Validation Service, I want to know how to deploy and maintain it so that it continue to be used by FNS after the engagement with 18F is over.

### Acceptance criteria

- [x] Start a doc
- [x] Evaluate how much of the [Demo Notes](https://docs.google.com/document/d/1A0xVmHTX-v5tYepIBEqgYvzRnMowG_TGFawFlmUErRM/edit#) to bring in
- [x] Establish the sections we should cover in this guide

**Comment by amymok** [comment]
Some items from the security checklist we need to perform:

- [ ] Recovery Guide:
  - Provide instructions on how to deploy and re-initialize the application.  This will be used as the recovery instruction:
    - Needs to document what is needed to perform recovery
    - There is still a need to re-initiate a database because of django-data-ingest
    - Reapply database migration
- [ ] Deployment Guide:
  - Provide instructions on how to deploy the system manually.

**Comment by mheadd** [comment]
I started to write this uo as a separate Google doc, but it didn't seem to make sense given that there is actually a lot of content in the repo that should be included in the guide. So I decided to use the project wiki as a home for this.

https://github.com/18F/usda-fns-ingest/wiki

Thoughts, @amymok, @juliaklindpaintner?

**Comment by amymok** [comment]
Wiki sounds like a good place.

**Comment by mheadd** [comment]
So I've incorporated most of our existing content into the [wiki](https://github.com/18F/usda-fns-ingest/wiki) in the `usda-fns-ingest` repo. A couple of outstanding issues to highlight:

* The [README](https://github.com/18F/usda-fns-ingest/blob/master/README.md) is probably obsolete, since all of the content is now in the wiki, and it's probably easier to maintain it in one place.
* There may be a delta between the `api.md` doc [in the repo](https://github.com/18F/usda-fns-ingest/blob/master/api.md), and one that @amymok has been updating in the [django-data-ingest](https://github.com/18F/django-data-ingest/blob/master/docs/api.md) repo. Not sure if the difference matters, but if it does we should use the most current version.
* There are some other docs in the `django-data-ingest` repo that I'm wondering if we should incorporate into the wiki. For example, can we use [this overview](https://github.com/18F/django-data-ingest/blob/master/docs/customize.md) on customization validation in the FNS wiki?

**Comment by amymok** [comment]
Thank you so much @mheadd .  I will definitely try to go over some of those to make updates.  I think one thing I have been thinking about as well is, do we actually want to duplicate some of documents from `django-data-ingest` to here.  Or should we just point to them there?  It means potentially everything will get outdated here.  But if we are locking down a `django-data-ingest` version, maybe it is better to have the outdated doc lives here because we are using that version here.

Any thoughts?

**Comment by mheadd** [comment]
@amymok Yeah, if we're locking down a `django-data-ingest` version for the FNS Data Validator, then maybe it makes sense for there to be a separate copy that is tailored to that version.

**Comment by juliaklindpaintner** [comment]
Thank you for this work, @mheadd! I agree it makes sense to have the separate copy here for FNS that can also build in more language that is specific to their use case and users.

**Comment by mheadd** [comment]
FYSA - I checked off the remaining acceptance criteria because I think we've done them. The guide isn't done, but I think we've finished identifying the sections to be included and incorporated as much of our current content as we can at this point.

**Comment by juliaklindpaintner** [comment]
Sounds good to me. Let's close this issue.
